import './styles/credits-styles.css';
import data from './creditsData';
import reactLogo from './images/logos/react-logo.png';
import gsapLogo from './images/logos/gsap-logo.svg'
import { FaGithub } from 'react-icons/fa6';

export default function Credits() {
    return (
        <div className="credits-wrapper">
            <div className="credits-container">
                <h2>Credits</h2>
                {data && data.length > 0 ?
                    data.map(item =>
                        <div className='credits-item' id={`credits-item-${item.id}`} key={`credits-item-${item.id}`}>
                            <span>{item.resource} from&nbsp;</span>
                            <a className='credits-author' href={item.author_url} rel='noopener noreferrer'>{item.author}</a>
                            {item.license !== 'No attribution needed' ?
                                <span id={`credits-license-${item.id}`} className='credits-license'>,&nbsp;<a className='license-link' href={item.license_url} rel='noopener noreferrer' style={{color: 'white'}}>{item.license}</a>&nbsp; license</span>
                            : null}
                        </div>
                    )
                    : null}
                    <p className='mock-text'>Mock website text generated by ChatGPT | All other work, e.g. website concept, structure and code, is my own.</p>
                    <div className='software-container'>
                        <h2>Made with:</h2>
                        <img className='software-item' id='react' src={reactLogo} alt='React' title='React'/>
                        <img className='software-item' id='gsap'src={gsapLogo} alt='GSAP' title='GSAP'/>
                        <div role='button' className='myGithub'>
                            <FaGithub id='github-logo'/>
                            <a className='myGithub-link' href='https://github.com/christinecollier' target='_blank' rel='noopener noreferrer'>
                                christinecollier
                            </a>
                        </div>
                    </div>
            </div>
        </div>
    );
}